"""add superadmin and custom prompts

Revision ID: 65da138a46ec
Revises: a3f1e2d4c890
Create Date: 2026-06-15 11:28:13.028764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65da138a46ec'
down_revision: Union[str, None] = 'a3f1e2d4c890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_configurations', sa.Column('clinical_system_prompt', sa.Text(), nullable=True))
    op.add_column('api_configurations', sa.Column('physical_system_prompt', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_column('users', 'is_superadmin')
    op.drop_column('api_configurations', 'physical_system_prompt')
    op.drop_column('api_configurations', 'clinical_system_prompt')
    # ### end Alembic commands ###
